# Generated by Django 4.1.7 on 2023-04-03 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='resumen',
            new_name='summary',
        ),
        migrations.RemoveField(
            model_name='project',
            name='field_name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='skills',
        ),
        migrations.AddField(
            model_name='project',
            name='Analysis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='Data_Mining',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='Machine_Learning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='SQL',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='State_of_art',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='Team_Work',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
