# Generated by Django 4.1.7 on 2023-04-04 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_resumen_project_summary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='area',
            field=models.CharField(choices=[('DS', 'Data Science'), ('PD', 'Product Development'), ('RS', 'Physics')], max_length=2),
        ),
    ]
